### ISSUE TITLE
Create unit tests and setup Travis CI.

### ISSUE THREAD

**Issue by dignifiedquire** [karma-runner/karma-junit-reporter#1]

**Comment by TheSavior** [comment]
The fact that this module has no tests is really disconcerting, especially seeing the number of bug reports and that versions have had regressions. We will be sadly pulling karma-junit-reporter out of our build system as it has caused too many flakes and issues. I hope you are able to prioritize setting up a test suite, even if it is just so tests can be added when fixing things to make sure they stay fixed.

**Comment by valera-rozuvan** [comment]
Currently, Travis CI build is failing:

![image](https://user-images.githubusercontent.com/2273090/39955788-f13c663a-55dd-11e8-894d-7aae423e0105.png)

**Comment by valera-rozuvan** [comment]
@treyhyde can you please take a look?

**Comment by hicom150** [comment]
Fixed 👍
