### ISSUE TITLE
Question about CLA and License

### ISSUE THREAD

**Issue by bduranc** [karma-runner/karma-junit-reporter#152]
Greetings,

I work for SAP and am currently helping a team who has expressed interest in using _karma-junit-reporter_.

We have a few questions related to the Contributor License Agreement found by following the hyperlink noted in the markdown file [_CONTRIBUTING.MD_.](https://github.com/karma-runner/karma-junit-reporter/blob/master/CONTRIBUTING.md) 

We have observed that the CLA referenced for this project is the _[Google Software Grant and Corporate Contributor License Agreement](http://code.google.com/legal/corporate-cla-v1.0.html)_ and we:

a) are curious what affiliation this project has with Google; and

b) seek confirmation for what license contributions to this project are governed under. I.e: Are all contributions automatically made under the MIT License as per the [_LICENSE_](https://github.com/karma-runner/karma-junit-reporter/blob/master/LICENSE) file, or is there a specific license not stated in the CLA? We ask this primarily because no such detail appears to be present in the CLA; and lastly

c) The license copyright text appears to have changed from "Vojta Jina and contributors" to "Google, Inc." at some [point in time](https://github.com/karma-runner/karma-junit-reporter/commit/a03c2f9f409fb5a466f12c0f062bbd653d0df79d). Is someone kindly able to provide detail around this change and clarify who the copyright holder is? We ask this primarily to identify/confirm who the original author is.

Your effort and time is appreciated. 
Thank you & kind regards,

Brian D.

**Comment by dignifiedquire** [comment]
Hey, I can give some details on this but as I am not affiliated with Google I can not speak for their legal situation. 

- Vojita Jina is the original author of karma itself and most of the other modules in this github organization, including karma-junit reporter.
- When he wrote this code he was working for Google, but left a few years back at which point the license changed to Google as he handed ownership to them.

**Comment by dignifiedquire** [comment]
- I am currently maintaining the project with the help of other contributors. 
- For more details on the Google side @zzo is probably the best person to answer questions.

**Comment by dignifiedquire** [comment]
- The license is always MIT for all code

**Comment by bduranc** [comment]
Thank you for your support.
