### ISSUE TITLE
reporter fails when browser times out

### ISSUE THREAD

**Issue by sylvain-hamel** [karma-runner/karma-junit-reporter#16]
steps to reproduce:
- configure `karmaconf.js` with `browserNoActivityTimeout : 1`
- activate `reporters: ['junit']`
- run tests

bug: karma crashes with this error

```
ERROR [karma]: [TypeError: Cannot call method 'att' of undefined]
```

**Comment by RaphiStein** [comment]
Happened to me too. I discovered that I was accidentally including the same files twice (overlap in my glob patterns) into the `preprocessors` config. When I fixed that, this issue was resolved.
