### ISSUE TITLE
Project Lifetime

### ISSUE THREAD

**Issue by byronmejia** [karma-runner/karma-junit-reporter#160]
Serious question: Is this project dead? Last commit wasn't since last year. Is there any way we can help make it more active?

**Comment by johnjbarton** [comment]
Review the existing pull requests and decide which ones should be closed or accepted. Figure out how to get the Travis CI to pass more often.

**Comment by hicom150** [comment]
I add a PR #165 where I update all the dependencies, remove deprecated libraries and fix some lintern errors. I think this could help to close some outdated PR's and help Travis pass more often 😉
Let me know if I can help in anything else 👍
