### ISSUE TITLE
Testcase name must be escaped

### ISSUE THREAD

**Issue by Pittan** [karma-runner/karma-junit-reporter#169]
# Current behavior
```
it('If user name contain <h1> will be no problem', () => {...})
```
will output as...
```
<testcase name="If user name contain <h1> will be no problem" time="0.029" classname="proj"/>
```

# Expected behavior
```
it('If user name contain <h1> will be no problem', () => {...})
```
will output as...
```
<testcase name="If user name contain &lt;h1&gt; will be no problem" time="0.029" classname="proj"/>
```

**Comment by hicom150** [comment]
According to [Canonical XML Specification](https://www.w3.org/TR/2000/WD-xml-c14n-20000119.html#charescaping) the correct output should be 
```
<testcase name="If user name contain &lt;h1> will be no problem" time="0.029" classname="proj"/>
```
as in attributes only `"<"`character should be replaced.

That is the exact result I'm getting with version `"karma-junit-reporter": 1.2.0`, could you @Pittan check if you are getting the same? 😉

**Comment by Pittan** [comment]
@hicom150 
Thank you for your reply 😀
I checked v1.2.0, and I saw the same result that you said above 🎉
