### ISSUE TITLE
Please consider releasing a new version.

### ISSUE THREAD

**Issue by ajssd** [karma-runner/karma-junit-reporter#176]
A number of tech firms have legal and security departments that periodically review the use of 3rd party libraries like this one, looking for libraries that considered "abandoned".  Now, I know karma-junit-reporter is not actually abandoned, but it hasn't had a release in almost 3 years, higher than the usual threshold of 2 years.

I see that there have been several PRs with updates to dependencies and such (e.g. #166, #167, among others) and some have been accepted and merged to master.

Is is possible for the owner of this repository to generate a release with a new version number?

**Comment by johnjbarton** [comment]
2.0.1 is available
