### ISSUE TITLE
Windows machines not reporting browser and OS

### ISSUE THREAD

**Issue by brion-fuller** [karma-runner/karma-junit-reporter#183]
I have karma tests that are running in Mac, Linux, and Windows.  

When I run my tests the output files are the following.
![image](https://user-images.githubusercontent.com/9418958/84299937-73d95d80-ab06-11ea-8a5e-d81d5274240a.png)

Current:
Output files are generic JUNIT-TESTS-<xx>.xml

Expected:
Output files should be \<Browser\> \<Browser version\> (\<OS\> \<OS version\>)

**Comment by jpaulin** [comment]
@brion-fuller 
Just checking.. I assume that you have same config in all the 3 OSes, ie. all have the same 'useBrowserName: true' config for
Karma junit reporter? Digging into the issue. Might be related to one other PR that's soon landing in the updated 
plugin.

**Comment by brion-fuller** [comment]
@jpaulin It looks like this issue is already fixed.  My test reports started displaying the browser name.  We can close this.  Sorry for the delay.
