### ISSUE TITLE
If browser is disconnected and not all tests run then it looks like all tests passed

### ISSUE THREAD

**Issue by novaterata** [karma-runner/karma-junit-reporter#29]
I have karma/qunit tests that involve Quicktime and other media plugins, so they crash alot. When this happens the browser disconnects and say 12 out of 92 tests run. I automate this with Jenkins and use karma-junit-reporter to report JUnit results, but outside of scraping the Console output afterwards it appears as if all tests passed and everything is fine. I've filed this issue with Karma, but thought it might be the responsibility of karma-junit-reporter instead.

**Comment by davidparsson** [comment]
That may actually be an issue on Jenkins' end. This reporter produces `errors="1"` in the XML report when a browser is disconnected.

See the full example below, produced by `karma-junit-runner` version 0.2.2, which is the latest version at time of writing:

    <?xml version="1.0"?>
    <testsuites>
      <testsuite name="PhantomJS 1.9.8 (Mac OS X)" package="tests" timestamp="2015-02-27T10:18:20" id="0" hostname="localhost" tests="1" errors="1" failures="0" time="0">
        <properties>
          <property name="browser.fullName" value="Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34"/>
        </properties>
        <system-out><![CDATA[
    ]]></system-out>
        <system-err/>
      </testsuite>
    </testsuites>

**Comment by davidparsson** [comment]
Jenkins ignores the `errors` attribute on the `testsuite` tag, but adding an `error` tag will make Jenkins see this error.
