### ISSUE TITLE
Running tests in succession results in nested browser directories

### ISSUE THREAD

**Issue by adamedwardsdbz** [karma-runner/karma-junit-reporter#52]
I started using the junit-reporter plugin in my angular js project and I notice that when I run the tests it starts creating nested Browser directories for each test result.

IE: 

First run of tests = "target/javascript/unit/PhantomJS/unit-test-results.xml"

Second run = "target/javascript/unit/PhantomJS/PhantomJS/unit-test-results.xml"

Third run = "target/javascript/unit/PhantomJS/PhantomJS/PhantomJS/unit-test-results.xml"

If I run my tests against multiple browsers, the nesting happens with each browser (IE - replace "PhantomJS" with "Chrome").

My configuration for the junitReporter looks like this:

<code>
junitReporter: {
            outputDir: '../target/javascript/unit',
            outputFile: 'unit-test-results.xml',
            suite: 'unit'
        }
</code>

Any help would be appreciated

**Comment by adamedwardsdbz** [comment]
Nevermind, not big enough of an issue to report.

If I set singleRun to be "true" then it overwrites the files as I would expect it to. 

However, if singleRun is "false" (which, as far as I can tell, is default in the WebStorm Karma plugin), then it creates these nested directories. Pretty much what I'm trying to say is that I may simply be an idiot and the plugin is working perfectly.

**Comment by spengilley** [comment]
This is still a problem for me. With default karma.conf.js setting of 

`junitReporter : {
        outputDir: '../', 
        outputFile: 'test-results.xml'
    },
`

karma-runner version 0.3.0
