### ISSUE TITLE
Set default value for outputDir

### ISSUE THREAD

**Issue by stevebroshar** [karma-runner/karma-junit-reporter#54]
I just upgraded karma-junit-reporter from v0.2.2 to v0.3.3.  Test runs fail with error: "You must set an output directory for JUnitReporter via the outputDir config property".  It seems that this setting had a default value before, but is now required.  Can we please revert to the default value?  It was working just fine.  Thanks.

**Comment by jatwork** [comment]
Experienced the same issue here. I believe the rewrite from v0.2.2 to 0.3.x breaks this:
https://github.com/karma-runner/karma-junit-reporter/compare/v0.2.2...v0.3.1

**Comment by Dignifiedquire** [comment]
If you want the old behaviour back, you can for now just set `outputDir: ''`.

**Comment by stevebroshar** [comment]
Thanks for feedback.  It's good to know that setting outputDir to blank results in the old behavior WRT where the file is written.  But, my suggestion is that the behavior should be like this by default ... that it should act as if outputDir is blank when it's not explicitly set.

**Comment by rcollette** [comment]
On my mac, the expression if (!reporterConfig.outputDir) evaluates to true with outputDir is set to ''.    There doesn't seem to be a workaround in my case.

**Comment by sfri** [comment]
Same problem here: !reporterConfig.outputDir evaluates to true on linux (Ubuntu 14.04)

**Comment by bra1n** [comment]
You could try by setting `outputDir: '.'` which will be the current directory. That removed the error message for me (on Mac) and did not affect the behaviour.
