### ISSUE TITLE
multiple test passes overwrites the test report

### ISSUE THREAD

**Issue by kburson** [karma-runner/karma-junit-reporter#6]
When you run multiple levels of tests (unit, midway / integration, e2e), each level of test is executed and overwrites the reports from the previous test runs.

It would be nice if the subsequent test runs would append rather than overwrite.

Workaround is to add a different test report name in the junitreporter config within each karma configuration block (once of unit, one for integration, one for e2e)

and yes, I know that karma e2e is on it's way out because it runs the tests in a frame, whereas protractor runs using selenium webdriver, hence protractor is being promoted as the e2e solution.  But, if you are still running ngScenario tests, you might want to configure test file reporters separately.

**Comment by hicom150** [comment]
Fixed 👍
