### ISSUE TITLE
XML output misses contexts

### ISSUE THREAD

**Issue by osherx** [karma-runner/karma-junit-reporter#62]
**having:** test suite that provides the following mocha output:

```
  client
    ✔ is cool
    ✔ is awsome
    client utility
      ✔ has absolutely no bugs
  Sender
    ✔ should be a module object
    ✔ should have API post(objRequest)
    using it
      get request
        ✖  should not fail
      POST request
        ✔ should not fail
```

**expected**: testcase name to include the context, like: 
`<testcase name="Sender using it get request should not fail" time="0.816" classname="Android_4_1_2_(Android_4_1_2).Sender">`
**but got:**
`<testcase name="should not fail" time="0.816" classname="Android_4_1_2_(Android_4_1_2).Sender">`

or, alternatively - if the format allows (im not sure what the JUnit xml spec sais) - then let `suite` nest context `suite` elements.
my personal hunch is that the first would be easier, and parsed by all builders that open JUnit xml files the same way they are parsed now :)

You can also look at failed tests of this build:
https://circleci.com/gh/el-net/bs_karma_eval/21
correspond to the code here:
https://github.com/el-net/bs_karma_eval

**Comment by maximumduncan** [comment]
We're seeing this too. It's causing our Bamboo server to miss tests as many tests appear to be named the same in the generated junit xml file.

Downgraded to karma-junit-reporter@0.3.3 for now as this doesn't exhibit this issue.

**Comment by NeverwinterMoon** [comment]
Same problem for us on Bamboo - with latest reporter version, out of 750 tests, Bamboo, after parsing, shows only 570 tests. With 2.2.2 Bamboo was showing a more realistic number (still not everything).

**Comment by Dignifiedquire** [comment]
Thanks for the report

**Comment by developit** [comment]
+1 would love to see a fix for this, or a tip on where to look if I were to try a PR ;)

**Comment by gunnx** [comment]
I noticed this too after upgrading, the classname used in the XML is only the top level "describe" any nested "describe" names are omitted, so tests group under the one level instead of splitting out.

**Comment by marty-buly** [comment]
This error was introduced by [e4f7ebd](https://github.com/karma-runner/karma-junit-reporter/commit/e4f7ebd). In order to generate Sonar compatible report, one have changed `result.suite.join(' ')` to `result.suite[0]`.

**Comment by phillipj** [comment]
Played with this locally and found that prefixing the test description with the parent suite names, ended it with the @osherx expected output test name.

From line [#125](https://github.com/karma-runner/karma-junit-reporter/blob/master/index.js#L125)
```js
var spec = suites[browser.id].ele('testcase', {
  name: result.suite.join(' ') + ' ' + result.description, // was result.description
  time: ((result.time || 0) / 1000),
  classname: getClassName(browser, result)
})
```
I could possibly open a PR with that fix if @Dignifiedquire thinks it looks good?

**Comment by jpaulin** [comment]
:+1:  for the idea of getting the nested describes working. We are also for now resorting to 0.3.3 downgrade most likely soon. I am writing a simple test for testing whether I could extinguish the bug; made by using that older working result.suite.join(' ') with enough sanity testing also so not to introduce new creepers. :) But so relative-newbie still (mostly in the tooling and philosophy of practical opensource) that I'll most likely be having a PR earliest 2016, if any.

**Comment by Dignifiedquire** [comment]
@phillipj sorry for the late reply but yes that sounds good

**Comment by jpaulin** [comment]
Can this be tested by test suites within the reporter? Ie. does karma-junit-reporter itself have tests? I was also a bit hesitant in putting forward a blind PR.

**Comment by jpaulin** [comment]
@Dignifiedquire Hi, has there been progress in this individual issue either through fix or the latest version containing changes? There's at least one pull request but the thing is that it should be tested with at least some known instances where the buggy 0.3.3 (-> onwards) name flattening happens. I didn't have test data at hand to test the PR.

**Comment by karniemi** [comment]
+1
