### ISSUE TITLE
multiple test runs cause ENOENT error

### ISSUE THREAD

**Issue by perrydt** [karma-runner/karma-junit-reporter#68]
After upgrading to 0.3.5 or 0.3.6, when running karma from gulp with singleRun = false:
```javascript
  new karma.Server({
    configFile: __dirname + '/webpack/karma.conf.js',
    singleRun: false,
  }, done).start()
```

And the following reporter configuration: 
```javascript
    junitReporter: {
      outputDir: 'build/tests',
    },
```

The first execution succeeds, but upon detecting file changes, the subsequent test runs fail:
```
29 09 2015 17:06:02.040:WARN [reporter.junit]: Cannot write JUnit xml
	ENOENT: no such file or directory, open '/home/xxxx/dev/xxxxx/build/tests/PhantomJS_1.9.8_(Linux_0.0.0)/home/xxxx/dev/xxxx/build/tests/TESTS-PhantomJS_1.9.8_(Linux_0.0.0).xml'
```
(edit: I was trying a few things to fix it and pasted the wrong error path originally)

It appears to be trying to append the full original output path to the new one.

Downgrading to version 0.3.4 fixes the problem.

**Comment by famoraes** [comment]
I'm facing the same issue here.

**Comment by nobodyman** [comment]
FYI: I no longer get this error after upgrading to 0.3.7.
