### ISSUE TITLE
Allow name and classname generation override

### ISSUE THREAD

**Issue by mleonh** [karma-runner/karma-junit-reporter#75]
Looking at issues such as #62 and #69, it certainly seems like different users of this plugin have different needs concerning how the testcase attributes 'name' and 'classname' are generated. In our case, a recent change introduced in e4f7ebd is pretty much the exact opposite of what we need.

It should be easy to allow users to add functions to their configs to handle this – in other words, for the  'classname' attribute we'd allow overriding the 'getClassName' function, and add something similar for 'name'.

Would you accept a PR for this if I implement it?

**Comment by irfanraza** [comment]
I agree with @mleonh 
We had a requirement to generate different classname but this was not possible. Finally I had to process the xml file again to make it acceptable.
